Zope 4 fixes.
zopefoundation/Products.PluggableAuthService pull request #4
Opened 2017-02-06 17:25 UTC by jensens

Fixes made in order to work with Zope 4, includes some common findings.

2017-02-08 16:21 UTC, icemac commented
It would be nice to see if these changes pass on Travis, see #5 which still requires Travis CI to be switched on for this repository.

2017-02-08 19:53 UTC, icemac commented
Travis is enabled now, could you please rebase your PR to the current master?

2017-02-19 23:12 UTC, jensens commented
rebased

tests are red, seems like a returned 302 signature and actual headers are different (so not wrong afaict).

2017-08-10 16:57 UTC, tseaver commented on setup.py
> +          'ZServer',
Why are we pulling in `ZSevrver`?  For WebDAV stuff?  If so, we should make it an optional dependency (i.e., an "extra" called `webdav`) and ensure that imports are conditional, tests are skipped, etc. if it is missing.

2017-08-10 16:57 UTC, tseaver commented on Products/PluggableAuthService/plugins/tests/ChallengeProtocolChooser.txt
> -  <BLANKLINE>
This doesn't look correct:  there *should* be a blank line between the headers and the payload.

2017-08-10 16:57 UTC, tseaver commented on Products/PluggableAuthService/plugins/tests/ChallengeProtocolChooser.txt
> +  HTTP/1.1 302 Found...
Wouldn't it be better to use the ellipsis to allow both messages?

2017-08-10 16:58 UTC, tseaver commented on setup.py
> +          'ZServer',
Why pull in `ZServer` as an unconditional dependency?  If it is for WebDAV stuff, then we should add a `webdav` extra and ensure that imports are conditional, tests are skipped, etc. if it is missing.

2017-08-14 06:15 UTC, icemac commented on setup.py
> +          'ZServer',
You are right, I created #8 to fix this, so this PR does not get too big.

2017-08-14 06:16 UTC, icemac commented on Products/PluggableAuthService/plugins/tests/ChallengeProtocolChooser.txt
> +  HTTP/1.1 302 Found...
It was fixed in #7 the way you suggested it.

2017-08-14 06:17 UTC, icemac commented on setup.py
> +          'ZServer',
See #8.

2017-08-14 06:18 UTC, icemac requested changes
IMHO this PR should be merged after #7 is merged, as it does some of its fixes again.

2017-08-17 06:07 UTC, icemac commented
Now after #7 is merged to master this PR could be rebased to the master.

2017-08-21 09:30 UTC, icemac approved these changes

2017-08-21 09:30 UTC, merged

2017-08-21 09:32 UTC, icemac commented
@jensens Can I safely delete the branch – as I merged it to master  – or will this break some integration tests?

2017-08-31 11:25 UTC, icemac commented
I decided to delete the branch to signal that the integration tests now should use the master branch.